### ISSUE TITLE
Not able to install with Cakephp 3.6 ?

### ISSUE THREAD

**Issue by amitjoc** [inimist/cakephp3-captcha#1]
i am using cakephp 3.6 version and when i try to download using following composer command 

**composer require inimist/cakephp-captcha:dev-master**

Bellow Error 

> Your requirements could not be resolved to an installable set of packages.
>  Problem 1
>   - Installation request for inimist/cakephp-captcha dev-master -> satisfiable by inimist/cakephp->captcha[dev-master].
>   - inimist/cakephp-captcha dev-master requires cakephp/cakephp ^3.7.0 -> satisfiable by >cakephp/cakephp[3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2] but these conflict with > your requirements or minimum-stability.

kindly see why it is not working with cakephp 3.6 version 
or if any other command is needed then please mention it. 
Thanks :)

**Comment by inimist** [comment]
Is there any problem upgrading to CakePHP 3.7? I think you should update, it does not have much changes. If there is any it must be for good only :)

**Comment by inimist** [comment]
I have change the CakePHP version requirement to 3.5 so you should be able to install it. I haven't done any compatibility test with 3.5 however. I recommend to keep yourself up with the latest version of CakePHP.

**Comment by amitjoc** [comment]
Thanks :+1: 
Now it is working.

**Comment by inimist** [comment]
Great. Let me know if you need any help :)
