### ISSUE TITLE
On Screen readers can read when height and width changed

### ISSUE THREAD

**Issue by karmicdice** [inimist/cakephp3-captcha#2]
In the URL
`localhost/create-captcha?type=image&field=Captcha&width=150&height=70&theme=default&length=6&1573225942650`

When width is changed to 15550

It displays the image which can easily be read by on-screen readers.

Solution:
Having a max limit for height and width.

**Comment by karmicdice** [comment]
@inimist Is this being maintained?

**Comment by inimist** [comment]
Hi, yes. Updating it. We had holidays so. Thanks for checking this out. I will really appreciate further participation. Thanks
